### ISSUE TITLE
Add labels support

### ISSUE THREAD

**Issue by jordeu** [seqeralabs/tower-cli#230]
## Description

Add support to manage and add labels to `actions`, `pipelines`, `runs` and `compute-envs`.

### Label management

**Create**
```
tw labels add [OPTIONS]
   * -n, --name=<name>              Label name
     -w, --workspace=<workspace>    Workspace numeric identifier (TOWER_WORKSPACE_ID as default)
   -v, --value=<label value>
``` 

**Update**
``` 
tw labels update [OPTIONS]
    * -i, --id=<labelId>             Label identifier
      -w, --workspace=<workspace>    Workspace numeric identifier (TOWER_WORKSPACE_ID as default)
     -v, --value=<label value>
``` 

**Delete**
```
tw labels delete [OPTIONS]
   * -i, --id=<labelId>             Label identifier
     -w, --workspace=<workspace>    Workspace numeric identifier (TOWER_WORKSPACE_ID as default)
```

**List**
```
tw labels list [OPTIONS]
     * -w, --workspace=<workspace>   Workspace numeric identifier (TOWER_WORKSPACE_ID as default)
     -t, --type=<type>         Type of Label
     -f, --filter=<filter>         Show only labels that contain the given word.
         --page=<page>             Pages to display [default: 1].
         --offset=<offset>         Rows record offset [default: 0].
         --max=<max>               Maximum number of records to display [default: 100].
```

### Show labels

**Actions**

Add a labels section
```
tw actions view -i <action_id> --show-labels
```

Add a labels column
```
tw actions list --show-labels
```

**Pipelines**
``` 
tw pipelines view -i <pipeline_id> --show-labels
tw pipelines list --show-labels
```

**Runs**
```
tw runs view -i <id> --show-labels
tw runs list --show-labels
```

**Compute environments**
``` 
tw compute-envs view -i <id> --show-labels
tw compute-envs list --show-labels
```

### Manage labels on entities

```
tw [actions|pipelines|runs] labels -w () -i () -n () key1=value1,key2=value2 --operation=[set,append,delete] --no-create
```

### Set labels on entities add subcommand
```
tw [compute-envs|actions|pipelines] add ... --labels key1=valu1,...
```

## Doubts / Missing things

- Allow to filter lists by label. I propose to wait that it is possible to filter using the "search" syntax.
- Do we allow to import/export labels when using the import/export commands? 
- Allow to add labels when creating/updating resource? Or force to use always the attach/detach commands?

## Tasks

- [ ] create labels command
- [ ] update labels command
- [ ] delete labels command
- [ ] list labels command
- [ ] show labels section at actions view
- [ ] show labels column at actions list
- [ ] show labels section at pipelines view
- [ ] show labels column at pipelines list
- [ ] show labels column at runs list
- [ ] show labels section at runs view
- [ ] show labels section at compute-envs view
- [ ] show labels column at compute-envs list
- [ ] create manage labels subcommand at all entities
- [ ] add `--labels` option to all add subcommand

**Comment by kenibrewer** [comment]
I'd like to +1 the inclusion of compute environment resource labels for this issue.
