### ISSUE TITLE
Add release job to publish tower-cli to homebrew

### ISSUE THREAD

**Issue by munishchouhan** [seqeralabs/tower-cli#376]
As done in wave-cli, we will replicate the same functionality here to publish tower-cli to homebrew-tap 

```[tasklist]
### Tasks
- [x] Create a github token to publish brew formula from tower-cli repo to homebrew-tap repo
- [x] Add token in build.yml
- [x] Add brew packager in jreleaser
```
